[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "lib-sensor-encoding"
version = "0.1.1"
dependencies = [
  "msgpack",
  "paho-mqtt",
  "sty",
]

[tool.setuptools.packages]
find = {}
